[package]
name = "cw32-data-serde"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Project-authored upstream-compatible CW32 chip metadata model"

[dependencies]
regex = "1.12.3"
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
serde_yaml.workspace = true
