[package]
name = "cw32-comparator-reference-example"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace]
[features]
default = ["cw32l012c8t6"]
cw32l010f8p6 = ["embassy-cw32/cw32l010f8p6", "cw32-metapac/cw32l010f8p6"]
cw32l011k8t6 = ["embassy-cw32/cw32l011k8t6", "cw32-metapac/cw32l011k8t6"]
cw32l012c8t6 = ["embassy-cw32/cw32l012c8t6", "cw32-metapac/cw32l012c8t6"]

[dependencies]
embassy-cw32 = { path = "../../embassy-cw32", default-features = false, features = ["rt"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"

[build-dependencies]
cw32-metapac = { path = "../../cw32-metapac", default-features = false, features = ["metadata"] }

[profile.dev]
opt-level = "s"
debug = 0

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = 0
